apiVersion: v1
kind: Pod
metadata:
  name: nginxvol
spec:
  containers:
  - name: nginxvol
    image: nginx
    volumeMounts:
    name: nginxvol
     - mountPath: /etc/nginx/conf.d
    
  volumes:
  - name: nginxvol
    persistentVolumeClaim:
      claimName: tiptopvolumeconfd
# emptyDir: {​​}​​