apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"tiptopvolumeconfd"},"spec":{"accessModes":["ReadWriteMany"],"azureFile":{"readOnly":false,"secretName":"tiptop-pvc-secret","shareName":"tiptopdevpvc"},"capacity":{"storage":"5Gi"},"mountOptions":["dir_mode=0777","file_mode=0777","uid=1000","gid=1000","mfsymlinks","nobrl"],"storageClassName":"azurefile"}}
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2021-02-03T09:55:38Z"
  finalizers:
  - kubernetes.io/pv-protection
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:accessModes: {}
        f:azureFile:
          .: {}
          f:secretName: {}
          f:secretNamespace: {}
          f:shareName: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:mountOptions: {}
        f:persistentVolumeReclaimPolicy: {}
        f:storageClassName: {}
        f:volumeMode: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-02-03T09:55:38Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:pv.kubernetes.io/bound-by-controller: {}
      f:spec:
        f:claimRef:
          .: {}
          f:apiVersion: {}
          f:kind: {}
          f:name: {}
          f:namespace: {}
          f:resourceVersion: {}
          f:uid: {}
      f:status:
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-02-03T09:55:44Z"
  name: tiptopvolumeconfd
  resourceVersion: "944287"
  selfLink: /api/v1/persistentvolumes/tiptopvolume/confd
  uid: a3cb45e9-8fc1-44b3-9af7-e76189a2f31d
spec:
  accessModes:
  - ReadWriteMany
  azureFile:
    secretName: tiptop-pvc-secret
    secretNamespace: null
    shareName: tiptopdevpvc
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: tiptopvolumeconfd
    namespace: tiptop-dev-ns
    resourceVersion: "944285"
    uid: 14873cfd-2811-45cf-8d9f-0630328ea4ba
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  volumeMode: Filesystem
status:
  phase: Bound
