apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttnginx
  labels:
    app: ttnginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttnginx
  template:
    metadata:
      labels:
        app: ttnginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"        
        ports:
        - containerPort: 80
        volumeMounts:
        - name: tiptopvolumeconf
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: tiptopvolumeconf
        azureFile:
          secretName: tiptop-pvc-secret
          shareName: confd
          readOnly: false 